-- INSERT INTO PRODUCER (NAME) VALUES ('PRODUCER - 01')


-- create table producer (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id))

-- create table producer_metadata (data_type varchar(255), sample_data varchar(255), producer_id bigint not null, primary key (producer_id))